numero= input("Digite um numero de 0 a 9999: ")
print ("milhar: {}".format(numero[0]))
print ("centena: {}".format(numero[1]))
print ("dezena: {}".format(numero[2]))
print ("unidade: {}".format(numero[3]))
